name: Deploy React App to GitHub Pages

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install

      - name: build the project
        run: |
          npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: start server for testing the built app
        run: npm run preview

      - name: Run Playwright tests
        run: npm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Kill Server Process
        if: always()
        run: |
          kill $(lsof -t -i:3000)
        shell: bash
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          BRANCH: gh-pages
          FOLDER: dist
        env:
          PERMISSIONS_POLICY: ${{ env.PERMISSIONS_POLICY }}
