name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Get Permissions-Policy header
        id: get-permissions-policy
        run: |
          export PERMISSIONS_POLICY=$(curl -I https://apiknight.github.io/ApiKnight/ 2>&1 | grep '^Permissions-Policy' | sed -e 's/.*: //')
          echo "PERMISSIONS_POLICY=${PERMISSIONS_POLICY//interest-cohort/}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          BRANCH: gh-pages
          FOLDER: dist
        env:
          PERMISSIONS_POLICY: ${{ env.PERMISSIONS_POLICY }}
