name: Deploy React App to GitHub Pages
on:
  [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build
      - name: Remove 'interest-cohort' from Permissions-Policy
        run: |
          echo "::set-env name=PERMISSIONS_POLICY::$(curl -I https://apiknight.github.io/ApiKnight/ 2>&1 | grep '^Permissions-Policy' | sed -e 's/.*: //')"
          echo "PERMISSIONS_POLICY=${PERMISSIONS_POLICY//interest-cohort/}" >> $GITHUB_ENV
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          BRANCH: gh-page
          FOLDER: dist
