name: Deploy React App to GitHub Pages

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Get Branch Name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: git-checkout
        uses: actions/checkout@v3

      - name: pnpm-setup
        uses: pnpm/action-setup@v2

      - name: Install Dependencies
        run: |
          git clean -fdx & pnpm install

      - name: ESlint check
        run: |
          pnpm run lint:fix

      - name: build the project
        run: |
          pnpm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: start server for testing the built app
        run: nohup pnpm run preview &
             echo "Preview app started"
             sleep 12

      - name: Run Playwright tests
        run: pnpm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Kill Server Process
        if: always()
        run: |
          kill $(lsof -t -i:4173)
          echo ${{ steps.extract_branch.outputs.branch }}
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          BRANCH: gh-pages
          FOLDER: dist
        env:
          PERMISSIONS_POLICY: ${{ env.PERMISSIONS_POLICY }}
        if: github.event_name == 'push' && steps.extract_branch.outputs.branch == 'main'  # 仅在 main 分支上推送时触发